# [[file:../main.org::*CONFIGS][CONFIGS:1]]
# data: 'data'

# # Input
# reads: 'data/fastq'
# parental_phages: 'data/genomes/phage/parental.phage.merged.fasta'

data:
  reads: 'data/fastq'
  genomes:
    ecoli: 'data/genomes/bacteria/E_coli_bl21_noplasmid.fasta'
    merged: 'data/genomes/bacteria/parental_phages_and_Ecoli_bl21.fasta'
    bacteira: 'data/genomes/bacteria'
    phages: 'data/genomes/phage'

# Outputs
outputs:
  nanoplot:
    before: 'outputs/nanoplot/before_filter'
    after: 'outputs/nanoplot/after_filter'
  assemblies:
    minia: 'outputs/assemblies/minia'
    miniasm: 'outputs/assemblies/miniasm'

# PARAMETERS
results: 'results'

# minia
params:
  minia:
    kmer: 21
    abundance: 7
    min_contig_lenght: 20_000
    max_contig_lenght: 200_000
  filtlong:
    keep_percent: 98
    min_length: 20_000
  pggb:
    map-pct-id: 90
    n-mappings: 100
    segment-length: 1_000
# CONFIGS:1 ends here
