# [[file:../main.org::*CONFIGS][CONFIGS:1]]
data: 'data'

# Input
reads: 'data/fastq'
parental_phages: 'data/genomes/phage/parental.phage.merged.fasta'

# Outputs
outputs:
  nanoplot:
    before: 'outputs/nanoplot/before_filter'
    after: 'outputs/nanoplot/after_filter'
  assemblies:
    minia: 'outputs/assemblies/minia'
    miniasm: 'outputs/assemblies/miniasm'

# PARAMETERS

# minia
params:
  minia:
    kmer: 21
    abundance: 7
  filtlong:
    min_length: 20_000
    keep_percent: 98
# CONFIGS:1 ends here
