data: 'data'

# Input
reads: 'data/fastq'

# Outputs
outputs:
  nanoplot:
    before:
      'outputs/nanoplot/before_filter'
    after:
      'outputs/nanoplot/after_filter'
  assemblies:
    minia: 'outputs/assemblies/minia'
    miniasm: 'outputs/assemblies/miniasm'

# PARAMETERS

# minia
params:
  minia:
    kmer: 21
    abundance: 10
  filtlong:
    min_length: 1000
    keep_percent: 95
