# [[file:../main.org::*CONFIGS][CONFIGS:1]]
experiments:
  - 'TREE_1'
  - 'TREE_2'
  - 'TREE_3'
  - 'TREE_4'
  - 'TREE_5'
  - 'TREE_6'

sample_genomes: 'true'
sample_size: 100
tree_title: ''

mmseqs_phrogs_url:
  'https://phrogs.lmge.uca.fr/downloads_from_website/FAA_phrog.tar.gz'

data:
  reads: '/export/erikg/data/phage/reads'
  reads_suffix: '.merged.fastq.gz'
  genomes:
    ecoli: 'data/genomes/bacteria/E_coli_bl21_noplasmid.fasta'
    merged: 'data/genomes/bacteria/parental_phages_and_Ecoli_bl21.fasta'
    bacteira: 'data/genomes/bacteria'
    phages: 'data/genomes/phage'
    ecoli_and_phages: 'data/genomes/ecoli_bl21_DE_and_phages_merged.fasta.gz'

results:
  nanoplot:
    before: 'results/nanoplot/before_filter'
    after: 'results/nanoplot/after_filter'
  assemblies:
    minia: 'results/assemblies/minia'
    miniasm: 'results/assemblies/miniasm'

params:
  minia:
    kmer: 33
    # abundance: 4
    min_contig_lenght: 40_000
    max_contig_lenght: 50_000
    P1_abundance: 5
    P1_bp: 186778684
    cores: 10
  filtlong:
    keep_percent: 90
    min_length: 10_000
  pggb:
    map_pct_id: 95
    segment_length: 500
    block_length: 1_000
    min_match_len: 47
    transclose_batch: 10_000
  seqkit:
    min: 40_000
    max: 50_000
  graphaligner:
    dbtype: 'vg'
    seed_minimizer: 15
  removing_bacteria:
    map_pct_id: 90
    segment_length: 1_000
    block_length: 1_000
    min_qcov: 1
  fastani:
    frag_lenght: 500
  phanotate:
    out_format: 'fasta'

# Sample genomes from assembly
# CONFIGS:1 ends here
