# [[file:../main.org::*CONFIGS][CONFIGS:1]]
# data: 'data'

# # Input
# reads: 'data/fastq'
# parental_phages: 'data/genomes/phage/parental.phage.merged.fasta'

data:
  reads: 'data/fastq'
  genomes:
    ecoli: 'data/genomes/bacteria/E_coli_bl21_noplasmid.fasta'
    merged: 'data/genomes/bacteria/parental_phages_and_Ecoli_bl21.fasta'
    bacteira: 'data/genomes/bacteria'
    phages: 'data/genomes/phage'
    ecoli_and_phages: 'data/genomes/ecoli_bl21_DE_and_phages_merged.fasta'

# Results
results:
  nanoplot:
    before: 'results/nanoplot/before_filter'
    after: 'results/nanoplot/after_filter'
  assemblies:
    minia: 'results/assemblies/minia'
    miniasm: 'results/assemblies/miniasm'

# minia
params:
  minia:
    kmer: 31
    abundance: 5
    min_contig_lenght: 40_000
    max_contig_lenght: 50_000
    cores: 10
  filtlong:
    keep_percent: 90
    min_length: 10_000
  pggb:
    minia_sample_size: 1_000
    map_pct_id: 90
    segment_length: 1_000
    block_length: 0

# Sample genomes from assembly
# CONFIGS:1 ends here
